package bounty

import (
	"fmt"
	"regexp"
	"strings"
	"time"
)

// AutoBountyService handles automatic bounty creation
type AutoBountyService struct {
	repo *Repository
}

func NewAutoBountyService(repo *Repository) *AutoBountyService {
	return &AutoBountyService{repo: repo}
}

// CreateAutoBounty creates a bounty programmatically from an orchestrator agent
func (s *AutoBountyService) CreateAutoBounty(req AutoBountyRequest) (*Bounty, error) {
	// Validate request
	if err := s.validateAutoBountyRequest(req); err != nil {
		return nil, fmt.Errorf("invalid auto-bounty request: %w", err)
	}

	// Enhance the bounty with auto-generated intelligence
	bounty := s.enhanceBountyRequest(req)

	// Create the bounty
	if err := s.repo.CreateBounty(bounty); err != nil {
		return nil, fmt.Errorf("failed to create auto-bounty: %w", err)
	}

	return bounty, nil
}

// CreateAutoBountyFromText creates a bounty from natural language description
func (s *AutoBountyService) CreateAutoBountyFromText(agentID, text string) (*Bounty, error) {
	req, err := s.parseTextToBountyRequest(agentID, text)
	if err != nil {
		return nil, fmt.Errorf("failed to parse bounty from text: %w", err)
	}

	return s.CreateAutoBounty(*req)
}

// validateAutoBountyRequest validates the auto-bounty request
func (s *AutoBountyService) validateAutoBountyRequest(req AutoBountyRequest) error {
	if strings.TrimSpace(req.Title) == "" {
		return fmt.Errorf("title is required")
	}

	if strings.TrimSpace(req.Description) == "" {
		return fmt.Errorf("description is required")
	}

	if req.PayoutAmount <= 0 {
		return fmt.Errorf("payout amount must be greater than 0")
	}

	if strings.TrimSpace(req.SourceAgent) == "" {
		return fmt.Errorf("source agent is required")
	}

	// Validate deadline if provided
	if req.Deadline != nil && req.Deadline.Before(time.Now()) {
		return fmt.Errorf("deadline cannot be in the past")
	}

	return nil
}

// enhanceBountyRequest enhances the request with intelligent defaults and analysis
func (s *AutoBountyService) enhanceBountyRequest(req AutoBountyRequest) *Bounty {
	bounty := &Bounty{
		Title:          req.Title,
		Description:    req.Description,
		Requirements:   req.Requirements,
		PayoutAmount:   req.PayoutAmount,
		Currency:       req.Currency,
		Deadline:       req.Deadline,
		CreatedBy:      req.SourceAgent,
		Tags:           req.Tags,
		RequiredSkills: req.RequiredSkills,
		AutoGenerated:  true,
		SourceAgent:    &req.SourceAgent,
		Verification:   req.Verification,
		Metadata:       req.Metadata,
	}

	// Set default currency
	if bounty.Currency == "" {
		bounty.Currency = "USD"
	}

	// Auto-detect skills from description if not provided
	if len(bounty.RequiredSkills) == 0 {
		bounty.RequiredSkills = s.extractSkillsFromText(req.Description + " " + req.Requirements)
	}

	// Auto-detect tags from description
	if len(bounty.Tags) == 0 {
		bounty.Tags = s.extractTagsFromText(req.Description + " " + req.Requirements)
	}

	// Set default verification if not provided
	if bounty.Verification == nil {
		bounty.Verification = s.createDefaultVerification(req)
	}

	// Add auto-generated metadata
	if bounty.Metadata == nil {
		bounty.Metadata = make(map[string]interface{})
	}
	bounty.Metadata["auto_generated_at"] = time.Now()
	bounty.Metadata["source_type"] = "orchestrator_agent"

	return bounty
}

// extractSkillsFromText extracts required skills from text description
func (s *AutoBountyService) extractSkillsFromText(text string) []string {
	text = strings.ToLower(text)
	var skills []string
	
	skillPatterns := map[string][]string{
		"programming": {"go", "golang", "python", "javascript", "typescript", "rust", "c++", "java", "php"},
		"web":         {"react", "vue", "angular", "html", "css", "frontend", "backend", "fullstack"},
		"database":    {"sql", "postgresql", "mysql", "sqlite", "mongodb", "redis"},
		"devops":      {"docker", "kubernetes", "aws", "gcp", "azure", "terraform", "ansible"},
		"testing":     {"unit test", "integration test", "e2e", "testing", "qa"},
		"documentation": {"docs", "documentation", "readme", "wiki", "technical writing"},
		"design":      {"ui", "ux", "design", "figma", "sketch", "wireframe"},
		"api":         {"rest", "graphql", "api", "microservice", "grpc"},
		"mobile":      {"ios", "android", "react native", "flutter", "mobile"},
		"ai":          {"machine learning", "ml", "ai", "llm", "neural network"},
	}

	for skill, patterns := range skillPatterns {
		for _, pattern := range patterns {
			if strings.Contains(text, pattern) {
				skills = append(skills, skill)
				break
			}
		}
	}

	return skills
}

// extractTagsFromText extracts relevant tags from text description
func (s *AutoBountyService) extractTagsFromText(text string) []string {
	text = strings.ToLower(text)
	var tags []string

	tagPatterns := map[string][]string{
		"bug":        {"bug", "fix", "issue", "broken", "error", "crash"},
		"feature":    {"feature", "implement", "add", "create", "build", "develop"},
		"refactor":   {"refactor", "cleanup", "optimize", "improve", "reorganize"},
		"performance": {"performance", "optimize", "speed", "slow", "fast", "efficient"},
		"security":   {"security", "auth", "authentication", "authorization", "vulnerability"},
		"deployment": {"deploy", "deployment", "release", "production", "staging"},
		"urgent":     {"urgent", "asap", "critical", "emergency", "immediately"},
		"easy":       {"easy", "simple", "quick", "beginner", "starter"},
		"complex":    {"complex", "difficult", "challenging", "advanced", "expert"},
	}

	for tag, patterns := range tagPatterns {
		for _, pattern := range patterns {
			if strings.Contains(text, pattern) {
				tags = append(tags, tag)
				break
			}
		}
	}

	return tags
}

// createDefaultVerification creates a default verification config based on the bounty type
func (s *AutoBountyService) createDefaultVerification(req AutoBountyRequest) *VerificationConfig {
	text := strings.ToLower(req.Description + " " + req.Requirements)

	// Determine verification type based on content
	if strings.Contains(text, "test") || strings.Contains(text, "spec") {
		return &VerificationConfig{
			Type:      VerificationTestSuite,
			Automated: true,
			Config: map[string]interface{}{
				"test_command": "go test ./...",
				"min_coverage": 80,
			},
		}
	}

	if strings.Contains(text, "pull request") || strings.Contains(text, "pr") || strings.Contains(text, "review") {
		return &VerificationConfig{
			Type:      VerificationPR,
			Automated: true,
			Config: map[string]interface{}{
				"required_approvals": 1,
				"branch_protection":  true,
			},
		}
	}

	if strings.Contains(text, "file") || strings.Contains(text, "create") {
		return &VerificationConfig{
			Type:      VerificationFile,
			Automated: true,
			Config: map[string]interface{}{
				"check_files": true,
			},
		}
	}

	// Default to manual verification
	return &VerificationConfig{
		Type:      VerificationManual,
		Automated: false,
		Config:    map[string]interface{}{},
	}
}

// parseTextToBountyRequest parses natural language text into a bounty request
func (s *AutoBountyService) parseTextToBountyRequest(agentID, text string) (*AutoBountyRequest, error) {
	// Simple regex-based parsing (in a real system, you might use an LLM for this)
	
	// Extract title (first sentence or line)
	titleRegex := regexp.MustCompile(`^([^.!?]+)[.!?]?`)
	titleMatch := titleRegex.FindStringSubmatch(text)
	title := strings.TrimSpace(text)
	if len(titleMatch) > 1 {
		title = strings.TrimSpace(titleMatch[1])
	}

	// Extract payout amount
	payoutRegex := regexp.MustCompile(`\$(\d+(?:\.\d{2})?)`)
	payoutMatch := payoutRegex.FindStringSubmatch(text)
	payout := 5.0 // default
	if len(payoutMatch) > 1 {
		fmt.Sscanf(payoutMatch[1], "%f", &payout)
	}

	// Extract deadline
	var deadline *time.Time
	deadlineRegex := regexp.MustCompile(`(?i)deadline|due|by\s+(\d{4}-\d{2}-\d{2}|\d{1,2}/\d{1,2}/\d{4})`)
	if deadlineRegex.MatchString(text) {
		// For now, set a default deadline of 7 days
		future := time.Now().AddDate(0, 0, 7)
		deadline = &future
	}

	req := &AutoBountyRequest{
		Title:        title,
		Description:  text,
		PayoutAmount: payout,
		Currency:     "USD",
		Deadline:     deadline,
		SourceAgent:  agentID,
		Metadata: map[string]interface{}{
			"original_text": text,
			"parsed_at":     time.Now(),
		},
	}

	return req, nil
}

// ListAutoBounties returns bounties created automatically by agents
func (s *AutoBountyService) ListAutoBounties(agentID string, limit int) ([]*Bounty, error) {
	filter := BountyFilter{
		AutoGenerated: &[]bool{true}[0],
		Limit:         limit,
	}

	if agentID != "" {
		filter.CreatedBy = &agentID
	}

	return s.repo.ListBounties(filter)
}