package bounty

import (
	"time"
)

// Bounty represents a task that can be claimed and completed for payment
type Bounty struct {
	ID              string                 `json:"id" db:"id"`
	Title           string                 `json:"title" db:"title"`
	Description     string                 `json:"description" db:"description"`
	Requirements    string                 `json:"requirements" db:"requirements"`
	PayoutAmount    float64                `json:"payout_amount" db:"payout_amount"`
	Currency        string                 `json:"currency" db:"currency"`
	Deadline        *time.Time             `json:"deadline" db:"deadline"`
	Status          BountyStatus           `json:"status" db:"status"`
	CreatedAt       time.Time              `json:"created_at" db:"created_at"`
	UpdatedAt       time.Time              `json:"updated_at" db:"updated_at"`
	CreatedBy       string                 `json:"created_by" db:"created_by"`
	ClaimedBy       *string                `json:"claimed_by" db:"claimed_by"`
	ClaimedAt       *time.Time             `json:"claimed_at" db:"claimed_at"`
	CompletedAt     *time.Time             `json:"completed_at" db:"completed_at"`
	VerifiedAt      *time.Time             `json:"verified_at" db:"verified_at"`
	Tags            []string               `json:"tags" db:"tags"`
	RequiredSkills  []string               `json:"required_skills" db:"required_skills"`
	Tier            BountyTier             `json:"tier" db:"tier"`
	AutoGenerated   bool                   `json:"auto_generated" db:"auto_generated"`
	SourceAgent     *string                `json:"source_agent" db:"source_agent"`
	Verification    *VerificationConfig    `json:"verification" db:"verification"`
	Metadata        map[string]interface{} `json:"metadata" db:"metadata"`
}

// BountyStatus represents the current state of a bounty
type BountyStatus string

const (
	StatusOpen      BountyStatus = "open"
	StatusClaimed   BountyStatus = "claimed"
	StatusSubmitted BountyStatus = "submitted"
	StatusCompleted BountyStatus = "completed"
	StatusRejected  BountyStatus = "rejected"
	StatusCanceled  BountyStatus = "canceled"
	StatusDisputed  BountyStatus = "disputed"
)

// BountyTier represents the difficulty/value tier of a bounty
type BountyTier string

const (
	TierBronze    BountyTier = "bronze"
	TierSilver    BountyTier = "silver"
	TierGold      BountyTier = "gold"
	TierPlatinum  BountyTier = "platinum"
	TierLegendary BountyTier = "legendary"
)

// VerificationConfig defines how a bounty should be verified
type VerificationConfig struct {
	Type       VerificationType           `json:"type"`
	Automated  bool                       `json:"automated"`
	Config     map[string]interface{}     `json:"config"`
	Verifiers  []string                   `json:"verifiers"`
}

// VerificationType defines the type of verification
type VerificationType string

const (
	VerificationManual    VerificationType = "manual"
	VerificationTestSuite VerificationType = "test_suite"
	VerificationPR        VerificationType = "pr_approval"
	VerificationBenchmark VerificationType = "benchmark"
	VerificationFile      VerificationType = "file_exists"
	VerificationCustom    VerificationType = "custom"
)

// AutoBountyRequest represents a request to create an auto-bounty
type AutoBountyRequest struct {
	Title           string                 `json:"title" binding:"required"`
	Description     string                 `json:"description" binding:"required"`
	Requirements    string                 `json:"requirements"`
	PayoutAmount    float64                `json:"payout_amount" binding:"required,gt=0"`
	Currency        string                 `json:"currency"`
	Deadline        *time.Time             `json:"deadline"`
	Tags            []string               `json:"tags"`
	RequiredSkills  []string               `json:"required_skills"`
	SourceAgent     string                 `json:"source_agent" binding:"required"`
	Verification    *VerificationConfig    `json:"verification"`
	Metadata        map[string]interface{} `json:"metadata"`
}

// BountyFilter represents filters for querying bounties
type BountyFilter struct {
	Status         []BountyStatus `json:"status"`
	Tier           []BountyTier   `json:"tier"`
	Tags           []string       `json:"tags"`
	RequiredSkills []string       `json:"required_skills"`
	MinPayout      *float64       `json:"min_payout"`
	MaxPayout      *float64       `json:"max_payout"`
	CreatedBy      *string        `json:"created_by"`
	AutoGenerated  *bool          `json:"auto_generated"`
	Limit          int            `json:"limit"`
	Offset         int            `json:"offset"`
}

// GetTierFromPayout determines the bounty tier based on payout amount
func GetTierFromPayout(amount float64) BountyTier {
	switch {
	case amount < 1.0:
		return TierBronze
	case amount < 5.0:
		return TierSilver
	case amount < 20.0:
		return TierGold
	case amount < 100.0:
		return TierPlatinum
	default:
		return TierLegendary
	}
}